# RMVX_SCRIPT_INDEX: 274
# RMVX_SCRIPT_ID: 274
# RMVX_SCRIPT_NAME: CG PMD Multi-Hit Ownership Bridge v2.5.53
# RMVX_SOURCE_SHA256: 7b668610301c41e14cc3768663af041726ab816f7e11e88f042e12e609960687

#==============================================================================
# ■ CG PMD Multi-Hit Ownership Bridge v2.5.53
#------------------------------------------------------------------------------
# Production runtime bridge for RPG Maker VX / RGSS2.
#
# Root cause addressed:
# A Tankentai standby WAIT can finish while a battler is already becoming the
# owner of a new PMD multi-hit Action Sequence. In the losing race, that older
# WAIT publishes battler.play == "End" immediately before the new
# CG_PMD_MULTI_* sequence is installed. Scene_Battle can then consume the stale
# End and close the action before the PMD damage callbacks reach their Scene
# consumer.
#
# Ownership rule:
# Only at Spriteset_Battle#set_action, immediately before the original method
# calls Sprite_Battler#start_action, a real CG_PMD_MULTI_* handoff may discard
# a stale play == "End" belonging to the superseded standby action.
#
# Deliberately NOT touched:
# - PMD wait fields / legacy wait fields
# - active_action / action queue
# - legitimate End generated by the newly installed sequence
# - non-PMD or single-hit action sequences
# - any Scene_Battle callback, targeting, damage, Ability, or Move authority
#==============================================================================

$imported = {} if $imported == nil
$imported["ALBERT_CG_PMD_MultiHit_Ownership_Bridge"] = "2.5.53"

class Spriteset_Battle
  alias cg_v253_pmd_multi_ownership_set_action set_action
  def set_action(actor, index, kind)
    if kind.to_s.index("CG_PMD_MULTI_") == 0
      sprites = actor ? @actor_sprites : @enemy_sprites
      sprite = sprites[index] rescue nil
      battler = sprite.instance_variable_get(:@battler) rescue nil
      if battler && battler.active && battler.play == "End"
        battler.play = 0
      end
    end
    cg_v253_pmd_multi_ownership_set_action(actor, index, kind)
  end
end
